// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"app/dal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newManageLog(db *gorm.DB) manageLog {
	_manageLog := manageLog{}

	_manageLog.manageLogDo.UseDB(db)
	_manageLog.manageLogDo.UseModel(&model.ManageLog{})

	tableName := _manageLog.manageLogDo.TableName()
	_manageLog.ALL = field.NewField(tableName, "*")
	_manageLog.ID = field.NewInt32(tableName, "id")
	_manageLog.Action = field.NewString(tableName, "action")
	_manageLog.UID = field.NewInt32(tableName, "uid")
	_manageLog.Message = field.NewString(tableName, "message")
	_manageLog.IP = field.NewString(tableName, "ip")
	_manageLog.UserAgent = field.NewString(tableName, "user_agent")
	_manageLog.Status = field.NewInt32(tableName, "status")
	_manageLog.CreatedAt = field.NewTime(tableName, "created_at")

	_manageLog.fillFieldMap()

	return _manageLog
}

type manageLog struct {
	manageLogDo

	ALL       field.Field
	ID        field.Int32
	Action    field.String
	UID       field.Int32
	Message   field.String
	IP        field.String
	UserAgent field.String
	Status    field.Int32
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (m manageLog) As(alias string) *manageLog {
	m.manageLogDo.DO = *(m.manageLogDo.As(alias).(*gen.DO))

	m.ALL = field.NewField(alias, "*")
	m.ID = field.NewInt32(alias, "id")
	m.Action = field.NewString(alias, "action")
	m.UID = field.NewInt32(alias, "uid")
	m.Message = field.NewString(alias, "message")
	m.IP = field.NewString(alias, "ip")
	m.UserAgent = field.NewString(alias, "user_agent")
	m.Status = field.NewInt32(alias, "status")
	m.CreatedAt = field.NewTime(alias, "created_at")

	m.fillFieldMap()

	return &m
}

func (m *manageLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *manageLog) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["id"] = m.ID
	m.fieldMap["action"] = m.Action
	m.fieldMap["uid"] = m.UID
	m.fieldMap["message"] = m.Message
	m.fieldMap["ip"] = m.IP
	m.fieldMap["user_agent"] = m.UserAgent
	m.fieldMap["status"] = m.Status
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m manageLog) clone(db *gorm.DB) manageLog {
	m.manageLogDo.ReplaceDB(db)
	return m
}

type manageLogDo struct{ gen.DO }

func (m manageLogDo) Debug() *manageLogDo {
	return m.withDO(m.DO.Debug())
}

func (m manageLogDo) WithContext(ctx context.Context) *manageLogDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m manageLogDo) Clauses(conds ...clause.Expression) *manageLogDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m manageLogDo) Not(conds ...gen.Condition) *manageLogDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m manageLogDo) Or(conds ...gen.Condition) *manageLogDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m manageLogDo) Select(conds ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m manageLogDo) Where(conds ...gen.Condition) *manageLogDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m manageLogDo) Order(conds ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m manageLogDo) Distinct(cols ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m manageLogDo) Omit(cols ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m manageLogDo) Join(table schema.Tabler, on ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m manageLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m manageLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m manageLogDo) Group(cols ...field.Expr) *manageLogDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m manageLogDo) Having(conds ...gen.Condition) *manageLogDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m manageLogDo) Limit(limit int) *manageLogDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m manageLogDo) Offset(offset int) *manageLogDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m manageLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *manageLogDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m manageLogDo) Unscoped() *manageLogDo {
	return m.withDO(m.DO.Unscoped())
}

func (m manageLogDo) Create(values ...*model.ManageLog) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m manageLogDo) CreateInBatches(values []*model.ManageLog, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m manageLogDo) Save(values ...*model.ManageLog) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m manageLogDo) First() (*model.ManageLog, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageLog), nil
	}
}

func (m manageLogDo) Take() (*model.ManageLog, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageLog), nil
	}
}

func (m manageLogDo) Last() (*model.ManageLog, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageLog), nil
	}
}

func (m manageLogDo) Find() ([]*model.ManageLog, error) {
	result, err := m.DO.Find()
	return result.([]*model.ManageLog), err
}

func (m manageLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ManageLog, err error) {
	buf := make([]*model.ManageLog, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m manageLogDo) FindInBatches(result *[]*model.ManageLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m manageLogDo) Attrs(attrs ...field.AssignExpr) *manageLogDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m manageLogDo) Assign(attrs ...field.AssignExpr) *manageLogDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m manageLogDo) Joins(field field.RelationField) *manageLogDo {
	return m.withDO(m.DO.Joins(field))
}

func (m manageLogDo) Preload(field field.RelationField) *manageLogDo {
	return m.withDO(m.DO.Preload(field))
}

func (m manageLogDo) FirstOrInit() (*model.ManageLog, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageLog), nil
	}
}

func (m manageLogDo) FirstOrCreate() (*model.ManageLog, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageLog), nil
	}
}

func (m manageLogDo) FindByPage(offset int, limit int) (result []*model.ManageLog, count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	if limit <= 0 {
		return
	}

	result, err = m.Offset(offset).Limit(limit).Find()
	return
}

func (m manageLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m *manageLogDo) withDO(do gen.Dao) *manageLogDo {
	m.DO = *do.(*gen.DO)
	return m
}
