// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"app/dal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newManageRule(db *gorm.DB) manageRule {
	_manageRule := manageRule{}

	_manageRule.manageRuleDo.UseDB(db)
	_manageRule.manageRuleDo.UseModel(&model.ManageRule{})

	tableName := _manageRule.manageRuleDo.TableName()
	_manageRule.ALL = field.NewField(tableName, "*")
	_manageRule.ID = field.NewInt32(tableName, "id")
	_manageRule.Name = field.NewString(tableName, "name")
	_manageRule.Path = field.NewString(tableName, "path")
	_manageRule.Route = field.NewString(tableName, "route")
	_manageRule.Key = field.NewString(tableName, "key")
	_manageRule.Method = field.NewString(tableName, "method")
	_manageRule.Status = field.NewInt32(tableName, "status")
	_manageRule.Pid = field.NewInt32(tableName, "pid")
	_manageRule.Remark = field.NewString(tableName, "remark")
	_manageRule.CreatedAt = field.NewTime(tableName, "created_at")
	_manageRule.UpdatedAt = field.NewTime(tableName, "updated_at")

	_manageRule.fillFieldMap()

	return _manageRule
}

type manageRule struct {
	manageRuleDo

	ALL       field.Field
	ID        field.Int32
	Name      field.String
	Path      field.String
	Route     field.String
	Key       field.String
	Method    field.String
	Status    field.Int32
	Pid       field.Int32
	Remark    field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (m manageRule) As(alias string) *manageRule {
	m.manageRuleDo.DO = *(m.manageRuleDo.As(alias).(*gen.DO))

	m.ALL = field.NewField(alias, "*")
	m.ID = field.NewInt32(alias, "id")
	m.Name = field.NewString(alias, "name")
	m.Path = field.NewString(alias, "path")
	m.Route = field.NewString(alias, "route")
	m.Key = field.NewString(alias, "key")
	m.Method = field.NewString(alias, "method")
	m.Status = field.NewInt32(alias, "status")
	m.Pid = field.NewInt32(alias, "pid")
	m.Remark = field.NewString(alias, "remark")
	m.CreatedAt = field.NewTime(alias, "created_at")
	m.UpdatedAt = field.NewTime(alias, "updated_at")

	m.fillFieldMap()

	return &m
}

func (m *manageRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *manageRule) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["path"] = m.Path
	m.fieldMap["route"] = m.Route
	m.fieldMap["key"] = m.Key
	m.fieldMap["method"] = m.Method
	m.fieldMap["status"] = m.Status
	m.fieldMap["pid"] = m.Pid
	m.fieldMap["remark"] = m.Remark
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m manageRule) clone(db *gorm.DB) manageRule {
	m.manageRuleDo.ReplaceDB(db)
	return m
}

type manageRuleDo struct{ gen.DO }

func (m manageRuleDo) Debug() *manageRuleDo {
	return m.withDO(m.DO.Debug())
}

func (m manageRuleDo) WithContext(ctx context.Context) *manageRuleDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m manageRuleDo) Clauses(conds ...clause.Expression) *manageRuleDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m manageRuleDo) Not(conds ...gen.Condition) *manageRuleDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m manageRuleDo) Or(conds ...gen.Condition) *manageRuleDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m manageRuleDo) Select(conds ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m manageRuleDo) Where(conds ...gen.Condition) *manageRuleDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m manageRuleDo) Order(conds ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m manageRuleDo) Distinct(cols ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m manageRuleDo) Omit(cols ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m manageRuleDo) Join(table schema.Tabler, on ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m manageRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m manageRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m manageRuleDo) Group(cols ...field.Expr) *manageRuleDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m manageRuleDo) Having(conds ...gen.Condition) *manageRuleDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m manageRuleDo) Limit(limit int) *manageRuleDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m manageRuleDo) Offset(offset int) *manageRuleDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m manageRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *manageRuleDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m manageRuleDo) Unscoped() *manageRuleDo {
	return m.withDO(m.DO.Unscoped())
}

func (m manageRuleDo) Create(values ...*model.ManageRule) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m manageRuleDo) CreateInBatches(values []*model.ManageRule, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m manageRuleDo) Save(values ...*model.ManageRule) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m manageRuleDo) First() (*model.ManageRule, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageRule), nil
	}
}

func (m manageRuleDo) Take() (*model.ManageRule, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageRule), nil
	}
}

func (m manageRuleDo) Last() (*model.ManageRule, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageRule), nil
	}
}

func (m manageRuleDo) Find() ([]*model.ManageRule, error) {
	result, err := m.DO.Find()
	return result.([]*model.ManageRule), err
}

func (m manageRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ManageRule, err error) {
	buf := make([]*model.ManageRule, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m manageRuleDo) FindInBatches(result *[]*model.ManageRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m manageRuleDo) Attrs(attrs ...field.AssignExpr) *manageRuleDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m manageRuleDo) Assign(attrs ...field.AssignExpr) *manageRuleDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m manageRuleDo) Joins(field field.RelationField) *manageRuleDo {
	return m.withDO(m.DO.Joins(field))
}

func (m manageRuleDo) Preload(field field.RelationField) *manageRuleDo {
	return m.withDO(m.DO.Preload(field))
}

func (m manageRuleDo) FirstOrInit() (*model.ManageRule, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageRule), nil
	}
}

func (m manageRuleDo) FirstOrCreate() (*model.ManageRule, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ManageRule), nil
	}
}

func (m manageRuleDo) FindByPage(offset int, limit int) (result []*model.ManageRule, count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	if limit <= 0 {
		return
	}

	result, err = m.Offset(offset).Limit(limit).Find()
	return
}

func (m manageRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m *manageRuleDo) withDO(do gen.Dao) *manageRuleDo {
	m.DO = *do.(*gen.DO)
	return m
}
