// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameManageUser = "dt_manage_user"

// ManageUser mapped from table <dt_manage_user>
type ManageUser struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string    `gorm:"column:username;not null;default:''" json:"username"` // 用户名
	Password  string    `gorm:"column:password;not null;default:''" json:"password"` // 用户密码
	Key       string    `gorm:"column:key;not null;default:''" json:"key"`           // 密码盐
	Nickname  string    `gorm:"column:nickname;not null;default:''" json:"nickname"` // 用户昵称
	Email     string    `gorm:"column:email;not null;default:''" json:"email"`       // Email
	Remark    string    `gorm:"column:remark;not null;default:''" json:"remark"`     // 用户备注
	Avatar    string    `gorm:"column:avatar;not null;default:''" json:"avatar"`     // 头像
	Status    int32     `gorm:"column:status;not null;default:0" json:"status"`      // 状态: -1软删除,0待激活,1正常,2禁止
	IsSuper   int32     `gorm:"column:is_super;not null;default:0" json:"is_super"`
	Effective int32     `gorm:"column:effective;not null;default:0" json:"effective"` // 该时间之前签发的 Token 失效
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:NULL" json:"updated_at"`
}

// TableName ManageUser's table name
func (*ManageUser) TableName() string {
	return TableNameManageUser
}
