// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameManageRole = "dt_manage_role"

// ManageRole mapped from table <dt_manage_role>
type ManageRole struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null;default:''" json:"name"`    // 角色名
	Alias     string    `gorm:"column:alias;not null;default:''" json:"alias"`  // 角色别名，英文唯一
	Remark    string    `gorm:"column:remark;default:''" json:"remark"`         // 角色备注
	Creator   int32     `gorm:"column:creator;default:0" json:"creator"`        // 创建人
	Status    int32     `gorm:"column:status;not null;default:0" json:"status"` // 状态: 1正常,2禁止
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:NULL" json:"updated_at"`
}

// TableName ManageRole's table name
func (*ManageRole) TableName() string {
	return TableNameManageRole
}
