// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameManageRule = "dt_manage_rule"

// ManageRule mapped from table <dt_manage_rule>
type ManageRule struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;default:''" json:"name"`
	Path      string    `gorm:"column:path;default:''" json:"path"`
	Route     string    `gorm:"column:route;default:''" json:"route"`
	Key       string    `gorm:"column:key;default:''" json:"key"`
	Method    string    `gorm:"column:method;default:''" json:"method"`
	Status    int32     `gorm:"column:status;not null;default:0" json:"status"` // 状态: 1正常,2禁止
	Pid       int32     `gorm:"column:pid;not null;default:0" json:"pid"`       // 上级 ID
	Remark    string    `gorm:"column:remark;default:''" json:"remark"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp(3)" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:NULL" json:"updated_at"`
}

// TableName ManageRule's table name
func (*ManageRule) TableName() string {
	return TableNameManageRule
}
