// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameManageLog = "dt_manage_log"

// ManageLog mapped from table <dt_manage_log>
type ManageLog struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Action    string    `gorm:"column:action;default:''" json:"action"`
	UID       int32     `gorm:"column:uid;not null;default:0" json:"uid"` // 用户 ID
	Message   string    `gorm:"column:message;default:''" json:"message"` // 信息
	IP        string    `gorm:"column:ip;default:''" json:"ip"`
	UserAgent string    `gorm:"column:user_agent;default:''" json:"user_agent"`
	Status    int32     `gorm:"column:status;not null;default:0" json:"status"` // 状态: 0 待读,1 已读
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
}

// TableName ManageLog's table name
func (*ManageLog) TableName() string {
	return TableNameManageLog
}
