// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMigrationsLog = "dt_migrations_log"

// MigrationsLog mapped from table <dt_migrations_log>
type MigrationsLog struct {
	Version       int64     `gorm:"column:version;primaryKey;autoIncrement:false" json:"version"` // 主键
	MigrationName string    `gorm:"column:migration_name;default:NULL" json:"migration_name"`     // 迁移名称
	StartTime     time.Time `gorm:"column:start_time;default:NULL" json:"start_time"`             // 开始时间
	EndTime       time.Time `gorm:"column:end_time;default:NULL" json:"end_time"`                 // 结束时间
	Breakpoint    bool      `gorm:"column:breakpoint;not null;default:0" json:"breakpoint"`       // 断点
}

// TableName MigrationsLog's table name
func (*MigrationsLog) TableName() string {
	return TableNameMigrationsLog
}
